name: example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrolls_to_top:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true